#!/usr/bin/env escript
%%%-------------------------------------------------------------------
%%% @doc Generates `priv/agent_manifest.eterm' from the capability
%%% sentences in the sibling filters' `.app.src' files.
%%%
%%% For each `<FiltersDir>/<dir>/src/<app>.app.src', reads the
%%% `{application, Name, [{description, "..."} | ...]}' term, strips
%%% a leading "em_filter example for " / "rss_filter example for " /
%%% "atom_filter example for " prefix from the description (when
%%% present), and maps the OTP application name (the atom in the
%%% `{application, Name, ...}' head — this is what `em_filter:
%%% start_agent/3' and friends register as the live peer's `name',
%%% not necessarily the directory name) to the resulting capability
%%% sentence.
%%%
%%% Usage (from the Emquest repo root):
%%%   escript priv/gen_manifest.escript [FiltersDir] [OutFile]
%%%
%%% Defaults:
%%%   FiltersDir = ../filters       (EmergenceSystem/filters, sibling
%%%                                  of this Emquest checkout)
%%%   OutFile    = priv/agent_manifest.eterm
%%% @end
%%%-------------------------------------------------------------------

-define(PREFIXES, [<<"em_filter example for ">>,
                    <<"rss_filter example for ">>,
                    <<"atom_filter example for ">>]).

main(Args) ->
    ScriptDir = filename:dirname(escript:script_name()),
    {FiltersDir, OutFile} = args(Args, ScriptDir),
    AppSrcFiles = lists:sort(
        filelib:wildcard(filename:join(FiltersDir, "*/src/*.app.src"))),
    io:format("[gen_manifest] scanning ~s (~p .app.src file(s))~n",
              [FiltersDir, length(AppSrcFiles)]),
    Manifest = lists:foldl(fun(Path, Acc) ->
        case parse_app_src(Path) of
            {ok, Name, Desc} -> maps:put(Name, Desc, Acc);
            skip             -> Acc
        end
    end, #{}, AppSrcFiles),
    write_manifest(OutFile, Manifest),
    io:format("[gen_manifest] wrote ~p entries to ~s~n",
              [maps:size(Manifest), OutFile]).

args([], ScriptDir) ->
    {filename:join(ScriptDir, "../../filters"),
     filename:join(ScriptDir, "agent_manifest.eterm")};
args([FiltersDir], ScriptDir) ->
    {FiltersDir, filename:join(ScriptDir, "agent_manifest.eterm")};
args([FiltersDir, OutFile], _ScriptDir) ->
    {FiltersDir, OutFile}.

parse_app_src(Path) ->
    case file:consult(Path) of
        {ok, [{application, Name, Props}]} when is_atom(Name) ->
            case lists:keyfind(description, 1, Props) of
                {description, DescStr} when is_list(DescStr) ->
                    Desc = strip_prefix(list_to_binary(DescStr), ?PREFIXES),
                    {ok, atom_to_binary(Name, utf8), Desc};
                _ ->
                    io:format("[gen_manifest] skip (no description): ~s~n",
                              [Path]),
                    skip
            end;
        _ ->
            io:format("[gen_manifest] skip (unparsable): ~s~n", [Path]),
            skip
    end.

strip_prefix(Desc, []) -> Desc;
strip_prefix(Desc, [Prefix | Rest]) ->
    Len = byte_size(Prefix),
    case Desc of
        <<Prefix:Len/binary, Tail/binary>> -> Tail;
        _                                  -> strip_prefix(Desc, Rest)
    end.

write_manifest(OutFile, Manifest) ->
    Header =
        "%% -*- erlang -*-\n"
        "%% Generated by priv/gen_manifest.escript -- DO NOT EDIT BY HAND.\n"
        "%% Regenerate with: escript priv/gen_manifest.escript\n"
        "%%\n"
        "%% Maps each filter's OTP application name to a one-line capability\n"
        "%% sentence. Loaded by em_librarian at boot and embedded via\n"
        "%% hf_topics /embed to build the semantic filter routing index.\n",
    Body = io_lib:format("~p.~n", [Manifest]),
    ok = file:write_file(OutFile, [Header, Body]).
