%%%-------------------------------------------------------------------
%%% @doc em_librarian — semantic index of filter capabilities.
%%%
%%% Holds `#{FilterName => Embedding}', built from
%%% `priv/agent_manifest.eterm' (generated by
%%% `priv/gen_manifest.escript' from the filters' `.app.src'
%%% descriptions) and embedded via `em_hf:embed_many/1' (hf_topics
%%% `/embed', MiniLM). Used by `agent_router' to semantically match a
%%% query to the filters most likely to answer it.
%%%
%%% === Boot ===
%%%
%%% On `init/1' the whole manifest is embedded in one batch call. If
%%% hf_topics is unreachable at boot, the index starts empty (a
%%% warning is logged) rather than crashing the supervisor — the
%%% Router degrades to its own fallback until the index is populated.
%%%
%%% === Event-driven refresh ===
%%%
%%% There is no polling/idle loop. When the Router encounters a live
%%% peer name that is not yet in the index, it calls `ensure/1' with
%%% that name; the sentence is looked up in the manifest (or, if the
%%% peer isn't in the manifest, the bare name itself is embedded as a
%%% best-effort sentence) and the index gains that one entry.
%%% @end
%%%-------------------------------------------------------------------
-module(em_librarian).
-behaviour(gen_server).
-include_lib("kernel/include/logger.hrl").

-export([start_link/0, index/0, ensure/1, dim/0]).
-export([init/1, handle_call/3, handle_cast/2, handle_info/2, terminate/2]).

%%====================================================================
%% API
%%====================================================================

-spec start_link() -> {ok, pid()} | {error, term()}.
start_link() ->
    gen_server:start_link({local, ?MODULE}, ?MODULE, [], []).

%% @doc Return the current `#{FilterName => Embedding}' index.
-spec index() -> #{binary() => [float()]}.
index() ->
    gen_server:call(?MODULE, index, 5_000).

%% @doc Embed any of `Names' missing from the index (from the
%% manifest sentence, or the bare name as a fallback). Idempotent —
%% already-indexed names are left untouched.
-spec ensure([binary()]) -> ok.
ensure(Names) ->
    gen_server:call(?MODULE, {ensure, Names}, 10_000).

%% @doc Return the embedding dimension, or 0 when the index is empty.
-spec dim() -> non_neg_integer().
dim() ->
    gen_server:call(?MODULE, dim, 5_000).

%%====================================================================
%% gen_server callbacks
%%====================================================================

init([]) ->
    Manifest = load_manifest(),
    Index = build_index(Manifest),
    {ok, #{manifest => Manifest, index => Index}}.

handle_call(index, _From, #{index := Index} = State) ->
    {reply, Index, State};

handle_call({ensure, Names}, _From,
            #{manifest := Manifest, index := Index} = State) ->
    Missing = lists:usort(
        [N || N <- Names, is_binary(N), N =/= <<>>,
              not maps:is_key(N, Index)]),
    NewIndex = case Missing of
        [] -> Index;
        _  -> embed_missing(Missing, Manifest, Index)
    end,
    {reply, ok, State#{index => NewIndex}};

handle_call(dim, _From, #{index := Index} = State) ->
    Dim = case maps:values(Index) of
        [V | _] -> length(V);
        []      -> 0
    end,
    {reply, Dim, State};

handle_call(_Req, _From, State) ->
    {reply, {error, unknown_call}, State}.

handle_cast(_Msg, State) -> {noreply, State}.
handle_info(_Msg, State) -> {noreply, State}.
terminate(_Reason, _State) -> ok.

%%====================================================================
%% Internal
%%====================================================================

%% @private
%% @doc Load the manifest map from `priv/agent_manifest.eterm'.
%% Returns `#{}' (with a warning) if the priv dir or file can't be
%% read/parsed — the Librarian must never crash the supervisor.
load_manifest() ->
    case code:priv_dir(emquest) of
        Dir when is_list(Dir) ->
            Path = filename:join(Dir, "agent_manifest.eterm"),
            case file:consult(Path) of
                {ok, [Map]} when is_map(Map) ->
                    Map;
                {ok, _} ->
                    ?LOG_WARNING("[em_librarian] ~s: unexpected term shape",
                                 [Path]),
                    #{};
                {error, Reason} ->
                    ?LOG_WARNING("[em_librarian] could not read ~s: ~p",
                                 [Path, Reason]),
                    #{}
            end;
        {error, Reason} ->
            ?LOG_WARNING("[em_librarian] priv_dir(emquest) unavailable: ~p",
                         [Reason]),
            #{}
    end.

%% @private
%% @doc Embed the whole manifest in one batch call. Never crashes —
%% falls back to an empty index (with a warning) when hf_topics is
%% unreachable at boot.
build_index(Manifest) when map_size(Manifest) =:= 0 ->
    #{};
build_index(Manifest) ->
    {Names, Sentences} = lists:unzip(maps:to_list(Manifest)),
    case em_hf:embed_many(Sentences) of
        {ok, Vecs} when length(Vecs) =:= length(Names) ->
            maps:from_list(lists:zip(Names, Vecs));
        _ ->
            ?LOG_WARNING("[em_librarian] hf_topics unreachable at boot — "
                         "starting with an empty index (~p manifest "
                         "entries pending)", [map_size(Manifest)]),
            #{}
    end.

%% @private
%% @doc Embed the missing names (manifest sentence, or bare name as
%% fallback) and merge into the index. Leaves the index untouched on
%% failure (hf_topics still down).
embed_missing(Missing, Manifest, Index) ->
    Sentences = [maps:get(N, Manifest, N) || N <- Missing],
    case em_hf:embed_many(Sentences) of
        {ok, Vecs} when length(Vecs) =:= length(Missing) ->
            maps:merge(Index, maps:from_list(lists:zip(Missing, Vecs)));
        _ ->
            Index
    end.
